---
- name: Preparing Workstation
  hosts: localhost
  connection: local
  tasks:

  - name: add repo chromium
    apt_repository:
      repo: 'ppa:chromium-daily/stable'
      state: present
      update_cache: yes
    become: yes
    become_user: root

  - name: install chromium
    apt:
      name: chromium-browser
      state: present
    become: yes
    become_user: root